# version: "3.9"
services:
  db:
    image: timescale/timescaledb:latest-pg16
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: innovia
    ports: ["5432:5432"]
  redis:
    image: redis:7
    ports: ["6379:6379"]
  mosquitto:
    image: eclipse-mosquitto:2
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports: ["1883:1883"]
